# Generated by Django 6.0.3 on 2026-04-09 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=150)),
                ('department_description', models.TextField()),
                ('department_image', models.ImageField(upload_to='department/')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.SmallIntegerField()),
                ('education_status', models.CharField(max_length=150)),
                ('work_experience', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('doctor_description', models.TextField()),
                ('available_work_hours', models.SmallIntegerField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('doctor_image', models.ImageField(upload_to='doctor/')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.department')),
            ],
        ),
    ]
