# Generated by Django 5.2.7 on 2026-04-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_alter_department_id_alter_doctordetail_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=150)),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_mobile_number', models.CharField(max_length=15)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('prescription', models.ImageField(blank=True, null=True, upload_to='prescription/')),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
