# Generated by Django 5.2.7 on 2026-04-14 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_appointmentdetails_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentdetails',
            old_name='department',
            new_name='department_name',
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='doctor_full_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.doctordetail'),
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='doctor_name',
            field=models.CharField(max_length=150),
        ),
    ]
