# Generated by Django 5.2.7 on 2026-04-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_rename_department_appointmentdetails_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='doctor_name',
        ),
    ]
