# Generated by Django 5.2.7 on 2026-04-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_remove_appointmentdetails_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='doctor_full_name',
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='doctor_name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
